# Generated by Django 6.0.7 on 2026-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('mandi', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='per quintal', max_length=50)),
                ('change', models.CharField(default='0%', max_length=20)),
                ('status', models.CharField(default='up', max_length=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
