# Generated by Django 6.0.7 on 2026-09-16 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilehistory',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='profilehistory',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='profilehistory',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='profilehistory',
            name='old_value',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_history/'),
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilehistory',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
