# Generated by Django 6.1.1 on 2026-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
