# Generated by Django 6.1.1 on 2026-09-17 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('activity', models.CharField(choices=[('sowing', '🌱 Sowing'), ('irrigation', '💧 Irrigation'), ('fertilizer', '🧪 Fertilizer'), ('pesticide', '💊 Pest/Disease Control'), ('inspection', '🔍 Crop Inspection'), ('harvest', '🌾 Harvest'), ('other', '📌 Other')], max_length=30)),
                ('activity_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
