# Generated by Django 6.1.1 on 2026-09-17 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation_date', models.DateField()),
                ('irrigation_time', models.TimeField(blank=True, null=True)),
                ('water_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('water_source', models.CharField(choices=[('borewell', '💧 Borewell'), ('canal', '🌊 Canal'), ('river', '🏞️ River'), ('rainwater', '🌧️ Rainwater'), ('tank', '🛢️ Water Tank'), ('other', '📌 Other')], default='borewell', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
