# Generated by Django 6.0.7 on 2026-09-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('weather', 'Weather'), ('disease', 'Disease Detection'), ('treatment', 'Treatment'), ('market', 'Market Price'), ('mandi', 'Best Mandi'), ('crop', 'Crop Recommendation'), ('farming', 'Farming Tips'), ('reminder', 'Farm Reminder'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
